### ISSUE TITLE
Open editing options for the loading progress circles

### ISSUE THREAD

**Issue by escully27** [sandanat/vue-pdf-app#63]
**Please describe a feature/problem.**

Have been enjoying this project however the circular progress indicator colors have not changed color no matter what I do.

**Describe the solution you'd like**

I'm not sure if it's using a GIF or what at this point as I've been able to edit the css colors for every other component for the pdf viewer - just not he circular loading indicator.

**Describe alternatives you've considered**

**Additional context**

**Comment by sandanat** [comment]
Hi!
1. Take any progress bar or change color (stroke attribute) of the native vuePdfApp [progress bar](https://github.com/sandanat/vue-pdf-app/blob/master/src/assets/images/loading-icon.svg?short_path=5a145de)
2. Add this css into your project
```css
.pdf-app .pdfViewer .page .loadingIcon,
.pdf-app #findInput[data-status="pending"],
.pdf-app .toolbarField.pageNumber.visiblePageIsLoading {
  background-image: url(path-to-progress-bar) !important;
}
```

[Example](https://codesandbox.io/s/vue-pdf-app-custom-loading-icon-lwywk?file=/src/App.vue)
