### ISSUE TITLE
Compatibility with bootstrap

### ISSUE THREAD

**Issue by tlyau62** [sandanat/vue-pdf-app#98]
When apply with bootstrap 4.6, there are some mispositions on the viewer, which can also be tested on the demo site. 

Thus, I have created a workaround scss for such issue. Not sure if it can be merge to the master.

```scss
.pdf-app {
  #thumbnailView {
    width: 100%;

    .thumbnail .thumbnailImage {
      width: 100% !important;
      height: 100% !important;
    }

    .convasWrapper {
      width: 100% !important;
      height: 100% !important;
    }
  }

  .pdfViewer .page > * {
    width: 100% !important;
    height: 100% !important;
  }
}
```
